version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Running tests..."
      - pytest -v
  build:
    commands:
      - echo "Deploying website to S3..."
      - aws s3 cp index.html s3://eduvos-demo-website-863761415698/index.html --content-type text/html
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id E3SR98M2IMBFJ8 --paths "/*"
